### ISSUE TITLE
vue fiche jardin

### ISSUE THREAD

**Issue by EstLx** [0xnome/pldjardin#11]
- Affiche les infos (nom, lieux, description, ...) d'un jardin
- Liste des lopins du jardin
- Liste des membres du jardin
- Contacts des admins
- Messages du jardin

Membre jardin : 
- Quitter le jardin

Admins : 
- ajout lopin au jardin
- ajouter/supprimer membres
- éditer les infos
- nommer un nouvel admin
- si quitter le jardin et qu'il est le seul admin, pas possible, popup pour dire qu'il faut nommer un nouvel admin

**Comment by hverlin** [comment]
![image](https://cloud.githubusercontent.com/assets/9151470/14778988/42c9937e-0ad6-11e6-97fb-99c4a1ff4910.png)

**Comment by EstLx** [comment]
Balsamiq ok
![jardin_1](https://cloud.githubusercontent.com/assets/10867081/14788439/1dd861e4-0b08-11e6-93f2-537046c6d64d.PNG)
Si clic sur "voir tout" :
![jardin_2](https://cloud.githubusercontent.com/assets/10867081/14788440/1dfb5d16-0b08-11e6-9e35-c581784e4a85.PNG)
