### ISSUE TITLE
vue accueil

### ISSUE THREAD

**Issue by hverlin** [0xnome/pldjardin#5]

**Comment by EstLx** [comment]
- modal connexion
- modal inscription
  Membre connecté : 
- Accès à "mes jardins/lopins"
- Accès au profil

Bandeau toujours présent sur les vues

**Comment by hverlin** [comment]
Accueil utilisateur non connecté  
![image](https://cloud.githubusercontent.com/assets/9151470/14777606/781ca96a-0ace-11e6-9245-de92d40d949b.png)

Accueil utilisateur connecté
![image](https://cloud.githubusercontent.com/assets/9151470/14777586/5e443f58-0ace-11e6-9b30-b43f556c4f86.png)
